Fixes client disconnect with equipping hats on armor stands
kruthers/HatsPlugin pull request #1
Opened 2024-02-19 21:18 UTC by EpyonProjects

- Deletes AbstractPacket, since it's not being used anymore
- And excess booleans in HatChecking

2024-03-17 17:56 UTC, kruthers approved these changes

2024-03-17 17:56 UTC, kruthers requested changes
Could this be reverted, it was a case i had not finishing coding a change in

2024-03-17 18:28 UTC, EpyonProjects commented
like the whole thing?   Yeah, it was just a hotfix

2024-03-18 21:23 UTC, EpyonProjects commented on src/main/kotlin/com/kruthers/hats/utils/HatChecking.kt
> +        return item.mcStack.tag?.contains("ps_hats") == true
Revert this line

2024-03-23 16:49 UTC, merged